[package]
authors = [
  "Julien Doget <julien.doget@cosmian.com>",
  "Bruno Grieder <bruno.grieder@cosmian.com>",
  "Emmanuel Coste <emmanuel.coste@cosmian.com",
]
edition = "2021"
name = "abe_gpsw"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "abe_gpsw"

[dependencies]
cosmian_bls12_381 = "0.4.0"
eyre = "0.6"
ff = "0.9"
group = "0.9"
hex = "0.4"
rand = "0.8"
rand_hc = "0.3"
regex = "1.5.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sha3 = "0.9"
tracing = "0.1"
