name: Release Android

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release ${{ matrix.target }} for feature ${{ matrix.feature }}
    env:
      PROJECT_NAME_UNDERSCORE: abe_gpsw
      ARCHIVE_NAME: ${{ matrix.target }}_${{ matrix.feature }}
      TARGET_PATTERN: target/${{ matrix.target }}/release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-linux-android
            feature: ffi
            target_short_name: arm64-v8a
          - target: armv7-linux-androideabi
            feature: ffi
            target_short_name: armeabi-v7a
          - target: x86_64-linux-android
            feature: ffi
            target_short_name: x86_64
          - target: i686-linux-android
            feature: ffi
            target_short_name: x86
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup target add ${{ matrix.target }}
      - run: sudo apt-get install clang libclang-dev
      - run: cargo install cargo-ndk
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22b
      - name: Build release with feature ${{ matrix.feature }}
        uses: actions-rs/cargo@v1
        with:
          command: ndk
          args: --target ${{ matrix.target_short_name }} -o ./jniLibs build --release --lib --verbose --features ${{ matrix.feature }}
      - name: Create zip
        run: |
          zip ${{ env.ARCHIVE_NAME }} ${{ env.TARGET_PATTERN }}/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARCHIVE_NAME }}.zip
