name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release ${{ matrix.target }} for feature ${{ matrix.feature }}
    env:
      PROJECT_NAME_UNDERSCORE: abe_gpsw
      ARCHIVE_NAME: ${{ matrix.target }}_${{ matrix.feature }}
      TARGET_PATTERN: target/${{ matrix.target }}/release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            feature: ffi
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: sudo apt-get install gcc-mingw-w64
      - run: rustup target add ${{ matrix.target }}
      - name: Build release with feature ${{ matrix.feature }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --features ${{ matrix.feature }} --target ${{ matrix.target }}
      - run: cargo install cbindgen
      - run: bash cbindgen.sh target/${{ matrix.target }}/release ${{ env.PROJECT_NAME_UNDERSCORE }}
      - name: Create zip
        run: |
          zip ${{ env.ARCHIVE_NAME }} ${{ env.TARGET_PATTERN }}/*${{ env.PROJECT_NAME_UNDERSCORE }}*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARCHIVE_NAME }}.zip
