name: Release ios

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release ${{ matrix.target }} for feature ${{ matrix.feature }}
    env:
      PROJECT_NAME_UNDERSCORE: abe_gpsw
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            feature: ffi
          - target: x86_64-apple-darwin
            feature: ffi
          - target: aarch64-apple-ios
            feature: ffi
          # - target: armv7-apple-ios
          #   feature: ffi
          - target: x86_64-apple-ios
            feature: ffi
          # - target: i386-apple-ios
          #   feature: ffi
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup target add ${{ matrix.target }}
      - name: Build release with feature ${{ matrix.feature }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --features ${{ matrix.feature }} --target ${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}_${{ matrix.target }}_${{ matrix.feature }}
          path: target/${{ matrix.target }}/release/*${{ env.PROJECT_NAME_UNDERSCORE }}*
