name: Release WebAssembly

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release ${{ matrix.target }} for feature ${{ matrix.feature }}
    env:
      PROJECT_NAME_UNDERSCORE: abe_gpsw
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: wasm32-unknown-unknown
            feature: wasm_bindgen
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo install wasm-pack
      - run: rustup target add ${{ matrix.target }}
      - run: wasm-pack build --release --all-features
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}_${{ github.ref_name }}_${{ matrix.target }}_${{ matrix.feature }}
          path: pkg
